ci: adds schema check to pipeline workflow

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -18,6 +18,24 @@ jobs:
       - name: build
         run: cargo build --release
 
+  check-schema:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v5
+      - uses: ./.github/actions/rust-setup
+      - name: generate
+        run: cargo run --bin generate-schema
+      - name: check
+        run: |
+          if ! git diff --exit-code; then
+            git status
+            echo "❌ Error: Uncommitted changes detected after running generate-schema script."
+            echo "❌ Please run \"cargo run --bin generate-schema\" and commit changes"
+            exit 1
+          else
+            echo "✅ Schema is up-to-date"
+          fi
+
   lint:
     runs-on: ubuntu-latest
     steps:
